docker:
  image: "yegor256/java8"
decrypt:
  settings.xml: "repo/settings.xml.asc"
  pubring.gpg: "repo/pubring.gpg.asc"
  secring.gpg: "repo/secring.gpg.asc"
release:
  commanders:
    - gastaldi
  script: |
      curl -s https://packagecloud.io/install/repositories/github/git-lfs/script.deb.sh | sudo bash
      sudo apt-get install git-lfs
      git lfs install
      git lfs pull
      mvn -B release:prepare release:perform -DdevelopmentVersion=${dev} -DreleaseVersion=${tag} -Dtag=v${tag} -Plauncher-booster-catalog-service --settings ../settings.xml

